//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public System.Guid PK_EventID { get; set; }
        public string Name { get; set; }
        public System.DateTime Date { get; set; }
        public string Street { get; set; }
        public string Zipcode { get; set; }
        public string City { get; set; }
        public System.Guid FK_CompanyID { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
