//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promotion
    {
        public System.Guid PK_PromotionID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Start { get; set; }
        public Nullable<System.DateTime> Expiration { get; set; }
        public System.Guid FK_CompanyID { get; set; }
        public Nullable<System.Guid> FK_DiscountID { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Discount Discount { get; set; }
    }
}
