//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promotion
    {
        public System.Guid PK_PromotionID { get; set; }
        public string Title { get; set; }
        public string Image { get; set; }
        public string Description { get; set; }
        public System.DateTime Start { get; set; }
        public System.DateTime Expiration { get; set; }
        public System.Guid FK_CompanyID { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
